# Generated by Django 5.0 on 2023-12-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("gdp", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gdp_growth", models.DecimalField(decimal_places=2, max_digits=5)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("inflation_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("jobless_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("gov_budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("debt_gdp", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "current_account",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("population", models.IntegerField()),
            ],
        ),
    ]
